name: Deploy to Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.150.0
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Hugo CLI
        run: |
          wget --no-verbose -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: "Setup Pages #1"
        run: |
          mkdir public
          touch public/.nojekyll

      - name: "Setup Pages #2"
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: pnpm install

      - name: Build TinaCMS
        run: pnpm tinacms build
        env:
          NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.TINA_CLIENT_ID }}
          NEXT_PUBLIC_TINA_BRANCH: ${{ github.ref_name }}
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
          TINA_SEARCH_INDEXER_TOKEN: ${{ secrets.TINA_SEARCH_INDEXER_TOKEN }}

      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
